import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import NewInformation from "@/feature/NewInformation/NewInform";
import InformationList from "@/component/InformationList";
import { GetStaticPaths, GetStaticProps, NextPage } from "next";
import { Information, InformationRecord } from "@/utils/model";
import { dehydrate, useQuery } from "react-query";
import { queryClient } from "./_app";

const inter = Inter({ subsets: ["latin"] });

export const list: InformationRecord[] = [
  {
    id: 1,
    firstName: "Th",
    lastName: "Th",
    email: "th@th",
  },
  {
    id: 2,
    firstName: "Kh",
    lastName: "Ng",
    email: "kh@ng",
  },
];

const Home: NextPage = () => {
  const { data: informations, isLoading } = useQuery(["informations"], getList);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>PERSONAL INFORMATION</h1>
        <NewInformation />
        {informations && <InformationList informations={informations || []} />}
        {isLoading && <div>Loading...</div>}
      </main>
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  await queryClient.prefetchQuery(["informations"], getList);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
    revalidate: 10,
  };
};

const getList = async () => {
  await new Promise((resolve) => {
    setTimeout(resolve, 250);
  });
  return list;
};
