import Head from "next/head";
import { Suspense } from "react";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import InformationList from "@/component/InformationList";
import { GetServerSideProps, GetStaticPaths, GetStaticProps, NextPage } from "next";
import { Information, InformationRecord } from "@/utils/model";
import { dehydrate, useQuery } from "react-query";
import { queryClient } from "./_app";
import dynamic from "next/dynamic";
import Modal from "@/component/Modal/Modal";
import Link from "next/link";

const NewInformation = dynamic(
  () => import("@/feature/NewInformation/NewInform"),
  {
    ssr: false,
    loading: () => <div>Loading...</div>
  }
);

const inter = Inter({ subsets: ["latin"] });

export const list: InformationRecord[] = [
  {
    id: 1,
    firstName: "Th",
    lastName: "Th",
    email: "th@th",
  },
  {
    id: 2,
    firstName: "Kh",
    lastName: "Ng",
    email: "kh@ng",
  },
];

const Home: NextPage = () => {
  const { data: informations, isLoading } = useQuery(["informations"], getList);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Link href={'/fetch'}>Go to Fetch page</Link>
        <h1>PERSONAL INFORMATION</h1>

        <Modal modalName="New">
          {(handleClose) => (
              <NewInformation handleClose={handleClose} />
          )}
        </Modal>

        {informations && <InformationList informations={informations || []} />}
        {isLoading && <div>Loading...</div>}
      </main>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  await queryClient.prefetchQuery(["informations"], getList);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};

const getList = async () => {
  await new Promise((resolve) => {
    setTimeout(resolve, 250);
  });
  return list;
};
